"""Content negotiation config generation (Apache, nginx, w3id.org)."""

from __future__ import annotations

from pathlib import Path
from urllib.parse import urlparse

MIME_TYPES = {
    "ttl": "text/turtle",
    "jsonld": "application/ld+json",
    "nt": "application/n-triples",
    "owl": "application/rdf+xml",
}

FILE_NAMES = {
    "ttl": "ontology.ttl",
    "jsonld": "ontology.jsonld",
    "nt": "ontology.nt",
    "owl": "ontology.owl",
}


def _generate_htaccess(output_dir: Path, formats: list[str]) -> Path:
    lines = ["RewriteEngine On", ""]
    for fmt in formats:
        if fmt in MIME_TYPES:
            mime = MIME_TYPES[fmt]
            filename = FILE_NAMES[fmt]
            mime_pattern = mime.replace("+", r"\+")
            lines.append(f"# {mime}")
            lines.append(f"RewriteCond %{{HTTP_ACCEPT}} {mime_pattern}")
            lines.append(f"RewriteRule ^$ {filename} [R=303,L]")
            lines.append("")
    lines.append("RewriteRule ^$ index.html [R=303,L]")
    lines.append("")
    path = output_dir / ".htaccess"
    path.write_text("\n".join(lines))
    return path


def _generate_nginx(output_dir: Path, base_uri: str, formats: list[str]) -> Path:
    parsed = urlparse(base_uri)
    location = parsed.path or "/"
    lines = [f"location {location} {{"]
    for fmt in formats:
        if fmt in MIME_TYPES:
            mime = MIME_TYPES[fmt]
            filename = FILE_NAMES[fmt]
            mime_pattern = mime.replace("+", r"\+")
            lines.append(f'    if ($http_accept ~* "{mime_pattern}") {{ return 303 {location}/{filename}; }}')
    lines.append(f"    return 303 {location}/index.html;")
    lines.append("}")
    lines.append("")
    path = output_dir / "conneg.nginx.conf"
    path.write_text("\n".join(lines))
    return path


def _generate_w3id(output_dir: Path, base_uri: str, formats: list[str]) -> Path:
    lines = [
        "# w3id.org content negotiation config",
        f"# Generated by Blathers for {base_uri}",
        "",
        "RewriteEngine On",
        "",
    ]
    for fmt in formats:
        if fmt in MIME_TYPES:
            mime = MIME_TYPES[fmt]
            filename = FILE_NAMES[fmt]
            mime_pattern = mime.replace("+", r"\+")
            lines.append(f"RewriteCond %{{HTTP_ACCEPT}} {mime_pattern}")
            lines.append(f"RewriteRule ^$ {base_uri}/{filename} [R=303,L]")
            lines.append("")
    lines.append("# Hash IRIs: /prism#Term → /prism/index.html#Term")
    lines.append(f"RewriteRule ^$ {base_uri}/index.html [R=303,L]")
    lines.append("")
    path = output_dir / "w3id.htaccess"
    path.write_text("\n".join(lines))
    return path


def generate_conneg(
    output_dir: Path,
    generate: list[str],
    base_uri: str,
    formats: list[str],
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    if "htaccess" in generate:
        created.append(_generate_htaccess(output_dir, formats))
    if "nginx" in generate:
        created.append(_generate_nginx(output_dir, base_uri, formats))
    if "w3id" in generate:
        created.append(_generate_w3id(output_dir, base_uri, formats))
    return created
